version: "3.7"

volumes:
  dbdata:

services:
  webserver:
    container_name: oee-nabati-webserver-backend
    image: nginx:stable-alpine
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - "./config/nginx:/etc/nginx/conf.d"
      - "./log/nginx:/var/log/nginx"
    depends_on:
      - backend
    links:
      - backend
    restart: always

  loadbalancer:
    container_name: oee-nabati-loadbalancer-frontend
    image: nginx:stable-alpine
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - "./config/nginx-frontend:/etc/nginx/conf.d"
      - "./log/nginx-frontend:/var/log/nginx"
    depends_on:
      - frontend
    links:
      - frontend
    restart: always

  loadbalancer_tv:
    container_name: oee-nabati-loadbalancer-tv
    image: nginx:stable-alpine
    ports:
      - "${TV_PORT}:80"
    volumes:
      - "./config/nginx-tv:/etc/nginx/conf.d"
      - "./log/nginx-tv:/var/log/nginx"
    depends_on:
      - tv
    links:
      - tv
    restart: always

  database:
    container_name: oee-nabati-database
    image: mariadb:latest
    volumes:
      - "./config/mysql:/etc/mysql/conf.d"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    restart: always

  backend:
    container_name: oee-nabati-backend
    links:
      - database
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        # - NODE_ENV=${MODE}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
        - BACKEND_PORT=${BACKEND_PORT}
    environment:
      - TZ=${TZ}
    restart: always

  frontend:
    container_name: oee-nabati-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # - NODE_ENV=${MODE}
        - FRONTEND_PORT=${FRONTEND_PORT}
        - API_URL=${API_URL}
    restart: always

  tv:
    container_name: oee-nabati-tv
    build:
      context: ./tv
      dockerfile: Dockerfile
      args:
        # - NODE_ENV=${MODE}
        - TV_PORT=${TV_PORT}
        - API_URL=${API_URL}
    restart: always

  adminer:
    image: adminer
    depends_on:
      - database
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

  api:
    build:
      context: ./apiserver
      dockerfile: dev.dockerfile
    working_dir: /var/www
    volumes:
      - ./apiserver:/var/www
    restart: always

  web:
    build:
      context: ./
      dockerfile: nginx-server.dockerfile
    working_dir: /var/www
    # volumes_from:
    #   - api
    ports:
      - 8080:80

  dbqc:
    image: mariadb:10.4-bionic
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=qaqc
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=homestead
      - MYSQL_ROOT_PASSWORD=secret

  mobile:
    build:
      context: ./mobilepage
      dockerfile: mobile.dockerfile
      args:
        - NODE_ENV=production
        - APISERVER_URL=http://${APISERVER_URL}:8080/
    restart: always
    ports:
      - "8282:80"

  dashboard:
    build:
      context: ./webpage
      dockerfile: web.dockerfile
      args:
        - NODE_ENV=production
        - APISERVER_URL=http://${APISERVER_URL}:8080
    restart: always
    ports:
      - "80:80"
