version: '3.7'

services:
  webserver:
    container_name: oee-nabati-webserver
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - "./config/nginx:/etc/nginx/conf.d"
      - "./log/nginx:/var/log/nginx"
    depends_on:
      - frontend
    links:
      - frontend
    restart: always
  frontend:
    container_name: oee-nabati-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always