version: '3.7'

services:
  webserver:
    container_name: oee-nabati-webserver-backend
    image: nginx:stable-alpine
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - "./config/nginx:/etc/nginx/conf.d"
      - "./log/nginx:/var/log/nginx"
    depends_on:
      - backend
    links:
      - backend
    restart: always
  database:
    container_name: oee-nabati-database
    image: mariadb:latest
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    restart: always
  backend:
    container_name: oee-nabati-backend
    links:
      - database
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
      - NODE_ENV=${MODE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BACKEND_PORT=${BACKEND_PORT}
    restart: always
  frontend:
    container_name: oee-nabati-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${MODE}
        - FRONTEND_PORT=${FRONTEND_PORT}
        - API_URL=${API_URL}
  adminer:
    image: adminer
    depends_on:
      - database
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"