version: '3.7'

services:
  webserver:
    container_name: oee-nabati-webserver
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./config/nginx-gate:/etc/nginx/conf.d"
      - "./log/nginx-gate:/var/log/nginx"
    depends_on:
      - backend
    links:
      - backend
    restart: always
  database:
    container_name: oee-nabati-database
    image: mariadb:latest
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=mygetzu
      - MYSQL_PASSWORD=P@ssw0rd|mysql
      - MYSQL_DATABASE=ooe_nabati
      - MYSQL_ROOT_PASSWORD=P@ssw0rd|mysql
    restart: always
  backend:
    container_name: oee-nabati-backend
    links:
      - database
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"
    restart: always
  adminer:
    image: adminer
    depends_on:
      - database
    restart: always
    ports:
      - "8181:8080"